name: Lint

on: push

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4.2.2

            - uses: hadolint/hadolint-action@v3.1.0
              with:
                dockerfile: Containerfile
